-- Seed course data: ECE courses and common first-year engineering courses

-- First-year engineering courses
INSERT INTO public.courses (subject, catalog_number, code, title, description, units) VALUES
('MATH', '117', 'MATH 117', 'Calculus 1 for Engineering', 'Differential calculus, applications of derivatives, introduction to integral calculus.', 0.5),
('MATH', '119', 'MATH 119', 'Calculus 2 for Engineering', 'Integral calculus, sequences and series, differential equations.', 0.5),
('MATH', '115', 'MATH 115', 'Linear Algebra for Engineering', 'Systems of linear equations, matrices, vector spaces, eigenvalues.', 0.5),
('CHEM', '120', 'CHEM 120', 'General Chemistry 1', 'Atomic structure, chemical bonding, thermodynamics.', 0.5),
('CHEM', '123', 'CHEM 123', 'General Chemistry 2', 'Chemical kinetics, equilibrium, electrochemistry.', 0.5),
('PHYS', '115', 'PHYS 115', 'Mechanics', 'Kinematics, dynamics, energy, momentum, rotational motion.', 0.5),
('PHYS', '125', 'PHYS 125', 'Waves, Electricity and Magnetism', 'Oscillations, waves, electric and magnetic fields.', 0.5),
('ECE', '100', 'ECE 100', 'Electrical and Computer Engineering Practice', 'Introduction to ECE profession, ethics, and practice.', 0.5),
('ECE', '105', 'ECE 105', 'Physics of Electrical Engineering 1', 'Electrostatics, magnetostatics, DC circuits.', 0.5),
('ECE', '106', 'ECE 106', 'Physics of Electrical Engineering 2', 'AC circuits, electromagnetic fields, transmission lines.', 0.5),
('ECE', '140', 'ECE 140', 'Linear Circuits', 'Analysis of linear circuits, network theorems, AC steady state.', 0.5),
('ECE', '150', 'ECE 150', 'Fundamentals of Programming', 'Programming fundamentals using C++, data structures, algorithms.', 0.5),
('ECE', '155', 'ECE 155', 'Engineering Design with Embedded Systems', 'Embedded systems design, microcontrollers, sensors, actuators.', 0.5),
('ECE', '192', 'ECE 192', 'Engineering Economics and Impact on Society', 'Engineering economics, project evaluation, societal impact.', 0.5),
('ECE', '200', 'ECE 200', 'Electrical and Computer Engineering Practice 2', 'Advanced ECE practice, professional development.', 0.5),
('ECE', '205', 'ECE 205', 'Advanced Calculus for Electrical Engineers', 'Multivariable calculus, vector calculus, complex analysis.', 0.5),
('ECE', '207', 'ECE 207', 'Numerical Methods in Engineering', 'Numerical methods, MATLAB programming, engineering applications.', 0.5),
('ECE', '209', 'ECE 209', 'Electronic and Photonic Devices', 'Semiconductor devices, diodes, transistors, optoelectronics.', 0.5),
('ECE', '222', 'ECE 222', 'Digital Computers', 'Digital logic, computer organization, assembly language.', 0.5),
('ECE', '224', 'ECE 224', 'Embedded Microprocessor Systems', 'Microprocessor architecture, embedded systems programming.', 0.5),
('ECE', '240', 'ECE 240', 'Electronic Circuits 1', 'Amplifiers, operational amplifiers, frequency response.', 0.5),
('ECE', '250', 'ECE 250', 'Algorithms and Data Structures', 'Data structures, algorithm analysis, sorting, searching, graphs.', 0.5),
('ECE', '252', 'ECE 252', 'Systems Programming and Concurrency', 'Systems programming, processes, threads, concurrency.', 0.5),
('ECE', '290', 'ECE 290', 'Engineering Profession, Ethics, and Law', 'Professional ethics, engineering law, regulations.', 0.5),
('ECE', '300', 'ECE 300', 'Electrical and Computer Engineering Practice 3', 'Advanced professional practice, capstone preparation.', 0.5),
('ECE', '316', 'ECE 316', 'Probability and Random Processes', 'Probability theory, random variables, stochastic processes.', 0.5),
('ECE', '318', 'ECE 318', 'Signals and Systems', 'Continuous and discrete-time signals, system analysis, transforms.', 0.5),
('ECE', '327', 'ECE 327', 'Digital Systems Applications', 'Advanced digital design, FPGAs, system-on-chip.', 0.5),
('ECE', '350', 'ECE 350', 'Real-Time Operating Systems', 'RTOS concepts, scheduling, real-time systems design.', 0.5),
('ECE', '351', 'ECE 351', 'Compilers', 'Compiler design, lexical analysis, parsing, code generation.', 0.5),
('ECE', '354', 'ECE 354', 'Computer Architecture', 'Processor design, memory systems, parallel architectures.', 0.5),
('ECE', '356', 'ECE 356', 'Database Systems', 'Database design, SQL, transaction processing, distributed databases.', 0.5),
('ECE', '380', 'ECE 380', 'Analog Control Systems', 'Control system analysis, feedback, stability, design.', 0.5),
('ECE', '390', 'ECE 390', 'Engineering Design Project', 'Capstone design project, team-based engineering design.', 1.0),
('ECE', '400', 'ECE 400', 'Electrical and Computer Engineering Practice 4', 'Final professional practice, career preparation.', 0.5),
('ECE', '406', 'ECE 406', 'Digital Control Systems', 'Digital control, discrete-time systems, implementation.', 0.5),
('ECE', '409', 'ECE 409', 'Digital Signal Processing', 'Discrete-time signals, filters, FFT, applications.', 0.5),
('ECE', '450', 'ECE 450', 'Real-Time Concurrent Systems', 'Concurrent systems, distributed systems, real-time computing.', 0.5),
('ECE', '454', 'ECE 454', 'Distributed and Network Computing', 'Distributed systems, networking, cloud computing.', 0.5),
('ECE', '457', 'ECE 457', 'Cooperative and Adaptive Algorithms', 'Machine learning, adaptive algorithms, optimization.', 0.5),
('ECE', '458', 'ECE 458', 'Computer Security', 'Cryptography, network security, secure systems design.', 0.5),
('ECE', '459', 'ECE 459', 'Programming for Performance', 'Performance optimization, parallel programming, profiling.', 0.5),
('ECE', '480', 'ECE 480', 'Digital Control Applications', 'Advanced digital control, applications, implementation.', 0.5),
('ECE', '490', 'ECE 490', 'Engineering Design Project 2', 'Advanced capstone project, implementation and testing.', 1.0)
ON CONFLICT (subject, catalog_number) DO NOTHING;
